### ISSUE TITLE
No Tags Showing

### ISSUE THREAD

**Issue by theGhostJW** [atom-haskell/ide-haskell-hasktags#15]
First time I have used this for 6 months. 
No elements showing in search box when searching file or project.

- Windows 10
- Atom 1.23.3 x64
- ide hasktags 0.0.13
- builder stack

----

**Comment by lierdakil** [comment]
Works for me, but I'm on Linux.

1. Check developer console for errors, maybe there is some information there.
2. Check if keypresses aren't stolen by Atom's builtin `symbols-view` package (e.g. disable it temporarily, or run hasktags comands from command pallette instead of keyboard shortcuts)
3. In any case, also try building `hasktags` executable instead of relying on bundled `hasktags.js` option (or vice versa)

**Comment by theGhostJW** [comment]
Hi

Sorry for late reply.

I have just upgraded GHC and stack  and GHCmod (was having numerous issues with atom due to a pathologically slow version of GHC). Now on GHCversion 8.2.2

Most things seem to be working now but still no symbols in hasktags and repl (see below). Have disabled Atom built in symbols view.

Dev console is showing the following warnings:
```
warn @ util.ts:52
CP.execFile @ util.ts:72
exithandler @ child_process.js:214
emitTwo @ events.js:106
emit @ events.js:191
maybeClose @ internal/child_process.js:885
ChildProcess._handle.onexit @ internal/child_process.js:226
util.ts:52 haskell-ghc-mod warning: EXCEPTION: browse: module `ParserTest' cannot be found locally

warn @ util.ts:52
handleProcessWarning @ upi-consumer.ts:429
module.exports.Emitter.simpleDispatch @ <embedded>:65955
module.exports.Emitter.emit @ <embedded>:66071
disposables.add.backend.onWarning @ index.ts:346
module.exports.Emitter.simpleDispatch @ <embedded>:65955
module.exports.Emitter.emit @ <embedded>:66071
run @ ghc-modi-process-real.ts:119
_tickDomainCallback @ internal/process/next_tick.js:129
util.ts:52 haskell-ghc-mod warning: EXCEPTION: browse:
           module `ParserTestHelpers' cannot be found locally

warn @ util.ts:52
CP.execFile @ util.ts:72
exithandler @ child_process.js:214
emitTwo @ events.js:106
emit @ events.js:191
maybeClose @ internal/child_process.js:885
ChildProcess._handle.onexit @ internal/child_process.js:226
util.ts:52 haskell-ghc-mod warning: EXCEPTION: browse:
           module `ParserTestHelpers' cannot be found locally

warn @ util.ts:52
handleProcessWarning @ upi-consumer.ts:429
module.exports.Emitter.simpleDispatch @ <embedded>:65955
module.exports.Emitter.emit @ <embedded>:66071
disposables.add.backend.onWarning @ index.ts:346
module.exports.Emitter.simpleDispatch @ <embedded>:65955
module.exports.Emitter.emit @ <embedded>:66071
run @ ghc-modi-process-real.ts:119
_tickDomainCallback @ internal/process/next_tick.js:129
util.ts:52 haskell-ghc-mod warning: EXCEPTION: browse:
           module `ResultInterpreterTest' cannot be found locally

warn @ util.ts:52
CP.execFile @ util.ts:72
exithandler @ child_process.js:214
emitTwo @ events.js:106
emit @ events.js:191
maybeClose @ internal/child_process.js:885
ChildProcess._handle.onexit @ internal/child_process.js:226
util.ts:52 haskell-ghc-mod warning: EXCEPTION: browse:
           module `ResultInterpreterTest' cannot be found locally
```
I am a bit confused by these module xxx cannot be found locally messages because the packages build and test fine in stack and from the Haskell IDE menu.

The below was due to mis-configuration:
_Interestingly REPL has stopped working as well (loses the data entry field on invocation) but I'll hold off logging this in case its the same root cause_

**Comment by lierdakil** [comment]
ghc-mod does not support GHC 8.2, hence the warnings https://github.com/DanielG/ghc-mod/issues/900

Hasktags doesn't depend on ghc-mod in any way though, so this is unrelated.

Please try building hasktags executable.

Can't say anything about repl, that one definitely should work on GHC 8.2.

**Comment by theGhostJW** [comment]
OK will try the re-build within the next..

**Comment by theGhostJW** [comment]
1. cloned and built: https://github.com/MarcWeber/hasktags
2. put hasktags.exe in windows path
3. changed hasktags path in package settings to: hasktags.exe
=> WORKS !!

**Comment by theGhostJW** [comment]
Since it is working when configured with a compiled version of hasktags closing
