### ISSUE TITLE
No items are displayed

### ISSUE THREAD

**Issue by LukaHorvat** [atom-haskell/ide-haskell-hasktags#5]
So I've been using this package previously and it simply worked and now it doesn't.

I don't know what changed and when in stopped working but when do `Show Tags` it just says "No matches found". Is there some debug output that I can give you? I don't see anything related to hasktags in the developer console.

**Comment by lierdakil** [comment]
Just in case, you didn't recently update to Atom 1.7.0-beta0, did you?

**Comment by LukaHorvat** [comment]
Nope, I'm on 1.6

**Comment by lierdakil** [comment]
I messed up. Should be good in v0.0.3. Thanks for reporting.

**Comment by LukaHorvat** [comment]
Confirmed working! Awesome
