### ISSUE TITLE
Duplicate entries in the context menu

### ISSUE THREAD

**Issue by dniku** [atom-haskell/ide-haskell-hasktags#9]
![image](https://cloud.githubusercontent.com/assets/1315874/25333098/b055c4aa-28f1-11e7-9758-f32b7918d859.png)

There are two "go to declaration" entries in the context menu. The top one is presumably Atom's native one (and it doesn't work in Haskell projects); the bottom one comes from this plugin (and it works). Is there any way to merge them?

**Comment by lierdakil** [comment]
Thanks for reporting. Should be fixed in 0.0.12.
